name: GitHub Script
author: GitHub
description: Run simple scripts using the GitHub client
branding:
  color: blue
  icon: code
inputs:
  remote-secret-one:
    description: This will inherit a secret from the Action Repo
    required: false
  remote-secret-two:
    description: This will inherit a secret from the Action Repo
    default: ${{ github.token }}
    required: false
  passthrough-one:
    description: This will pass a secret or variable to the Action
    required: false
  passthrough-two:
    description: This will pass a secret or variable to the Action
    required: false
outputs:
  result:
    description: The return value of the script, stringified with `JSON.stringify`
runs:
  using: node16
  main: dist/index.js
