# This is a basic workflow to help you get started with Actions

name: Workflow-Wrap-Example

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:
    inputs:
      passthrough-one:
        description: 'something something deploy target' 
        type: string
        required: true
        default: 'prod'
      passthrough-two:
        description: 'something something env'    
        type: string
        required: true
        default: 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Use-Local-Action:
    uses: jasontiedt/github-script/.github/workflows/greet-everyone.yml@main
    with:
       local-variable-one: ${{ secrets.SECRET_ONE }}
       local-variable-two: ${{ secrets.SECRET_TWO }}
       passthrough-one: ${{ github.event.inputs.passthrough-one }}
       passthrough-two: ${{ github.event.inputs.passthrough-two }}
  
